logging:
    level:
        org:
            springframework: ERROR

management:
    endpoints:
        web:
            exposure:
                include: '*'

spring:

    devtools:
        restart:
            additional-paths: /resources
    mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
        
feign:
    client:
       url: https://api.openweathermap.org/data/2.5/forecast?q&appid=d2929e9483efc82c82c32ee7e02d563e

springdoc:
        api-docs:
            path: /api-docs
        swagger-ui:
              path: /swagger
jwt:
   secret: mykeys
   get:
    token:
      uri: /authenticate